name: Install dependencies
description: Install dependencies for all projects
inputs:
  nodejs-version:
    description: 'Nodejs version to use to deploy'
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.nodejs-version }}

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v3
      with:
        path: 'node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Install project dependencies if needed.
      #if: steps.cache-node-modules.outputs.cache-hit != 'true'
      shell: bash
      run: |
        npm install

    - name: Cache Cypress binary
      uses: actions/cache@v3
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-cypress-
