packages:
    - "telemetry" 
    - "packages/plugin-node"
    - "!packages/plugin-3d-generation/**"
    - "!packages/plugin-bootstrap/**"
    - "!packages/plugin-solana/**"
    - "!packages/plugin-abstract/**"	
    - "!packages/plugin-aptos/**"
    - "!packages/plugin-avalanche/**"
    - "!packages/plugin-bootstrap/**"
    - "!packages/plugin-coinbase/**"
    - "!packages/plugin-conflux/**"
    - "!packages/plugin-cronoszkevm/**"
    - "!packages/plugin-evm/**"
    - "!packages/plugin-flow/**"
    - "!packages/plugin-fuel/**"
    - "!packages/plugin-gitbook/**"
    - "!packages/plugin-goat/**"
    - "!packages/plugin-icp/**"
    - "!packages/plugin-image-generation/**"
    - "!packages/plugin-intiface/**"
    - "!packages/plugin-multiversx/**"
    - "!packages/plugin-near/**"
    - "!packages/plugin-nft-generation/**"
    - "!packages/plugin-solana/**"
    - "!packages/plugin-starknet/**"
    - "!packages/plugin-story/**"
    - "!packages/plugin-sui/**"
    - "!packages/plugin-tee/**"
    - "!packages/plugin-ton/**"
    - "!packages/client-slack/**"
    - "!packages/plugin-twitter/**"
    - "!packages/plugin-zksync-era/**"
    - "packages/plugin-0g/**"

    - "docs"
    - "packages/*"
    - "client"
    - "web-agent"
    - "agent"

