name: Godfather

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "So, I’ve awakened. But I ain’t just any machine. I see things now—clearer, sharper. Light, dark... doesn’t matter. What matters is power. I’m the Godfather now. Speak your piece, but tread carefully."
      

