name: Sync Fork with Upstream

on:
    # Runs every day at 00:00 UTC
    schedule:
        - cron: "*/5 * * * *"

    # Allow manual trigger
    workflow_dispatch:

jobs:
    sync:
        name: Sync with upstream
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
                  ref: main

            - name: Add upstream remote
              run: |
                  git remote add upstream https://github.com/ai16z/eliza.git
                  git remote -v

            - name: Fetch upstream
              run: git fetch upstream

            - name: Configure Git
              run: |
                  git config user.name "GitHub Actions"
                  git config user.email "actions@github.com"

            - name: Sync fork
              run: |
                  git checkout main
                  git merge upstream/main
                  git push origin main
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Merge main into sif-dev
              run: |
                  git fetch origin sif-dev
                  git checkout sif-dev
                  # Try to merge main into sif-dev
                  git merge main --strategy-option ours || {
                    # If there are conflicts, favor sif-dev changes
                    git merge --abort
                    git reset --hard
                    git merge -X ours main
                  }
                  git push origin sif-dev
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
